// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqkxxbyngazuyzeyihda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxa3h4YnluZ2F6dXl6ZXlpaGRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNDMxNTAsImV4cCI6MjA2NzYxOTE1MH0.21TEDY-_H9zAuL_hQPC3jC7NmSQRlfm2Fxo7AQ8d87g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});